spring.application.name=Product_Inventory_Catalog
spring.datasource.url=jdbc:mysql://localhost:3306/warehouse_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Samvas232
spring.datasource.dbcp2.driver-class-name= com.mysql.cj.jdbc.Driver

# Tells Hibernate to generate or modify tables automatically based on Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#server.port=8085