package com.FoodCart.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import com.FoodCart.util.DBConnection;


/*
 	The Data Access Object (DAO) pattern is a structural pattern that allows us to isolate the application/business layer 
 	from the persistence layer (usually a relational database but could be any other persistence mechanism) using an abstract API.

	The API hides from the application all the complexity of performing CRUD operations in the underlying storage mechanism. 
	This permits both layers to evolve separately without knowing anything about each other.
*/

/*
 	ResultSet: 
 	
 	A table of data representing a database result set, which is usually generated by executing a statement that queries the database.

	A ResultSet object maintains a cursor pointing to its current row of data. Initially the cursor is positioned before the first row. 
	The next method moves the cursor to the next row, and because it returns false when there are no more rows in the ResultSet object,
 	it can be used in a while loop to iterate through the result set.
 */

public class LoginDAO {

	public boolean validate(String userName, String passWord) {

		// Check User entered credentials with DB stored credentials;

		boolean status = false;

		try {
			Connection con = DBConnection.getConnection();

			PreparedStatement p_stmt = con.prepareStatement("select * from users where username = ? and password = ?");

			System.out.println("LoginDAO Debug :: userName = "+ userName);
			System.out.println("LoginDAO Debug :: password = "+ passWord);

//			See the question marks in the p_smt initialization? The below commands are used to substitute that
			p_stmt.setString(1,userName);
			p_stmt.setString(2,passWord);

//			Result set stores the view returned by query
//			executeQuery returns a ResultSet object that contains the data produced by the query; never null
			ResultSet rs = p_stmt.executeQuery();

			status = rs.next();
			System.out.println("LoginDAO Debug :: login_status = "+ status);
		}catch(Exception e) { 
			System.out.println("LoginDAO :: QueryExeution Error :: " + e.getMessage());
		}
		return status;
	}

}
